<div class="footer-navigation">
    <div class="row">
        <nav class="nav">
            <a class="nav-link" href="/">Home</a>
            <a class="nav-link" href="/products">Products</a>
            <a class="nav-link" href="/contact">Contact</a>
        </nav>
        <nav class="nav">
           <!-- <a class="nav-link" href="#" style="font-weight: 500">Privacy Policy</a>-->
           <!-- <a class="nav-link" href="#" style="font-weight: 500">Terms & Conditions</a>-->
            <!--
            <a class="nav-link" href="#">Blog</a>
            <a class="nav-link" href="#">Support</a>
            <a class="nav-link" href="#">Wholesale</a>
            <a class="nav-link" href="#">Affiliates</a>
            -->
        </nav>
    </div>
</div>
