<div class="footer-social">
    <p>Get social with us!</p>

    <a href="#" rel="me">
        <img src='<?php echo $this->getViewFileUrl('images/icon-fb.svg'); ?>' alt="Facebook Icon">
    </a>
    <a href="#" rel="me">
        <img src='<?php echo $this->getViewFileUrl('images/icon-ig.svg'); ?>' alt="Instagram Icon">
    </a>
    <!--
    <a href="#" rel="me">
        <img src='<?php echo $this->getViewFileUrl('images/icon-tw.svg'); ?>' alt="Twitter Icon">
    </a>
    -->
</div>
