<section class="behind-the-brand">
    <div class="top-banner">
        <img src="<?= $block->getViewFileUrl('images/cms/page/about/top-banner.png') ?>">
    </div>
    <div class="content centered">
        <img src="<?= $block->getViewFileUrl('images/cms/page/about/flamingo.png') ?>" srcset="<?= $block->getViewFileUrl('images/cms/page/about/flamingo@2x.png') ?> 2x" class="flamingo">
        <img src="<?= $block->getViewFileUrl('images/cms/page/about/behind-the-brand.png') ?>" srcset="<?= $block->getViewFileUrl('images/cms/page/about/behind-the-brand@2x.png') ?> 2x" class="section-title">
        <p>
            Our primary purpose at Mingo Rad is to provide the purest & most high-quality
            CBD products available. We take pride in the steps we require to carefully extract
            cannaboid compounds from our…. filler content here to round out this paragraph.
        </p>
    </div>
</section>

<section class="our-passion">
    <div class="row">
        <div class="content left">
            <img src="<?= $block->getViewFileUrl('images/cms/page/about/our-passion.png') ?>" srcset="<?= $block->getViewFileUrl('images/cms/page/about/our-passion@2x.png') ?> 2x" class="section-title">
            <p>
                Let’s get one thing straight, we’re here to help heal.
                No additives. No GMO’s. No harsh chemicals. Just pure, clean CBD with a fresh
                new take on flavor. By combining naturally occuring CBD with a funky twist of
                natural flavors, we believe we’ve landed on something that goes against the
                mainstream current!
            </p>
        </div>
    </div>
</section>

<section class="our-purpose">
    <div class="row">
        <div class="content right">
            <img src="<?= $block->getViewFileUrl('images/cms/page/about/our-purpose.png') ?>" srcset="<?= $block->getViewFileUrl('images/cms/page/about/our-purpose@2x.png') ?> 2x" class="section-title">
            <p>
                A happy go-lucky group of people came together with one goal in mind:
                Finding a way to take a more natural approach to healing. And we found
                our beach. If you’re looking for a fresh new flavor vibe that’ll never harsh
                your mellow, you’ve come to the right stop.
            </p>
        </div>
    </div>
</section>

<section class="our-promise">
    <div class="row">
        <div class="content left">
            <img src="<?= $block->getViewFileUrl('images/cms/page/about/our-promise.png') ?>" srcset="<?= $block->getViewFileUrl('images/cms/page/about/our-promise@2x.png') ?> 2x" class="section-title">
            <p>
                They say the proof is in the pudding. The only problem? We don’t
                make pudding. ———— No additives about it. We stand behind
                our products so much that we offer a really great 30-day guarantee
                that I don’t yet have the details on, but I will get them shortly!
            </p>
        </div>
    </div>
</section>

<section class="shop-now">
    <div class="row">
        <div class="left-content">
            <div class="v-center">
                <img src="<?= $block->getViewFileUrl('images/cms/page/about/naturally-good-vibes.png') ?>" srcset="<?= $block->getViewFileUrl('images/cms/page/about/naturally-good-vibes@2x.png') ?> 2x">
                <a href="#">
                    <img src="<?= $block->getViewFileUrl('images/cms/page/about/btn-shop-now.png') ?>" srcset="<?= $block->getViewFileUrl('images/cms/page/about/btn-shop-now@2x.png') ?> 2x">
                </a>
            </div>
        </div>
        <div class="right-content">
            <picture>
                <source media="(max-width: 768px)" srcset="<?= $block->getViewFileUrl('images/cms/page/about/bottles-sm.png') ?>, <?= $block->getViewFileUrl('images/cms/page/about/bottles-sm@2x.png') ?> 2x">
                <img src="<?= $block->getViewFileUrl('images/cms/page/about/bottles.png') ?>" srcset="<?= $block->getViewFileUrl('images/cms/page/about/bottles@2x.png') ?> 2x">
            </picture>
        </div>
    </div>
</section>
