<?php /** @var \Magento\Newsletter\Block\Subscribe $block */ ?>

<div class="block newsletter">
    <div class="title">
        <span class="desktop">Catch Our Newsletter</span>
        <span class="mobile">Catch Our Latest News and Offers Here:</span>
    </div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <label class="label" for="newsletter"><span><?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?></span></label>
                <div class="control">
                    <input name="email" type="email" id="newsletter"
                                placeholder="<?= $block->escapeHtmlAttr(__('Your Email Address')) ?>"
                                data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary" title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>" type="submit">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                    <img src="<?php echo $this->getViewFileUrl('images/icon-arrow.svg'); ?>">
                </button>
            </div>
        </form>
    </div>
</div>
